ktor {
    deployment {
        port = 8081
    }

    application {
        modules = [ com.filmapp.ApplicationKt.module ]
    }
}

jwt {
    secret = "super_secret_jwt_key"
    issuer = "filmapp"
    audience = "filmapp-users"
    realm = "filmapp-realm"
    expiration = 86400000   // ← ДОБАВЬТЕ ЭТУ СТРОКУ (время жизни токена в миллисекундах)
}

database {
    driver = "org.postgresql.Driver"
    jdbcUrl = "jdbc:postgresql://localhost:5432/filmdb"
    user = "filmuser"
    password = "filmpassword"
}